package it.parttimeteam.view.utils

object Strings {
  final var CLEAR_SELECTION_BTN = "Clear Selection"
  final var CREATE_PRIVATE_CODE = "Create a private code"
  final var ERROR_DIALOG_TITLE = "Error"
  final var GAME_ENDED_ALERT_TITLE = "Game ended"
  final var GAME_END_PLAYER_LEFT_MESSAGE = s"The game ended. Another player left the game. Do you want to play again?"
  final var GAME_LOADING_MESSAGE = "Preparing your cards..."
  final var GAME_LOADING_TITLE = "Game loading"
  final var GAME_WON_ALERT_MESSAGE = "Congratulations! You won the game! Do you want to play again?"
  final var HERE_IS_YOUR_CODE = "Here is your code"
  final var INPUT_MISSING_DIALOG_TITLE = "Input missing"
  final var INPUT_MISSING_USER_CODE_DIALOG_MESSAGE = "You must enter both username and code."
  final var INPUT_MISSING_USER_NUM_DIALOG_MESSAGE = "You must enter username and select players number."
  final var JOIN_WITH_CODE = "Join with a code"
  final var LEAVE_GAME_BTN = "Leave Game"
  final var LEAVE_GAME_DIALOG_MESSAGE = "Are you sure you want to leave the game? The action cannot be undone."
  final var LEAVE_GAME_DIALOG_TITLE = "Leave the game"
  final var MAKE_COMBINATION_BTN = "Make Combination"
  final var OTHER_PLAYERS = "Other players:"
  final var PASS_AND_DRAW_BTN = "Pass & Draw"
  final var PASS_BTN = "Pass"
  final var PICK_CARDS_BTN = "Pick Cards"
  final var RESET_BTN = "Reset"
  final var SELECT_PLAYERS_NUM = "Select players number"
  final var SEND = "Send"
  final var SORT_RANK_BTN = "Sort Rank"
  final var SORT_SUIT_BTN = "Sort Suit"
  final var START_NEW_GAME = "Start new game"
  final var TIMER = "Timer"
  final var TIMER_END_INFO_MESSAGE = "You haven't passed your turn. We will pass and draw a card for you."
  final var TIME_IS_UP = "Your time is up!"
  final var UPDATE_COMBINATION_BTN = "Update Combination"
  final var USERNAME = "Username"
  final var WAITING_FOR_PLAYERS = "Waiting for other players"
  final var YOUR_TURN = "Your turn"
  final var YOUR_TURN_ALERT_MESSAGE = "It's your turn"

  final def GAME_LOST_ALERT_MESSAGE(winnerUsername: String): String = s"This game has a winner. And the winner is.. $winnerUsername! Do you want to play again?"
  final def PLAYER_TURN_MESSAGE(playerName: String): String = s"It's $playerName turn"

  object Error {
    final val CARD_NOT_CONTAINED_IN_HAND = "Hand doesn't contains a card you selected."
    final val COMBINATION_NOT_VALID = "Invalid combination."
    final val LOBBY_CODE_NOT_VALID = "The code is not valid."
    final val NOT_VALID_PLAY = "Invalid play in this turn."
    final val NO_CARD_IN_BOARD = "Board doesn't contains a card you selected."
    final val SERVER_NOT_FOUND = "Server not found."
    final val UNEXPECTED_ERROR = "An unexpected error occurred."
  }
}
