# Info about vm and jvm.
language: scala # The project language.

jdk:
  - openjdk11 # Java version. Add other Java versions under this.

install: true

scala:
  # 2.12.11 # Scala version. Add other Scala versions under this.
  - 2.12.8

git:
  autocrlf: input

# These directories are cached to S3 at the end of the build.
cache:
  directories:
    - $HOME/.ivy2/cache
    - /tmp/texlive
    - $HOME/.texlive
    - $HOME/.cache/coursier
    - $HOME/.sbt

notifications:
  email:
    recipients:
      - daniele.tentoni.1996@gmail.com
      - mcavalluzzo.dev@gmail.com
      - lorenzo.pagnini@yahoo.com
      - lucagiorgit@virgilio.it
    on_failure: always
    on_success: change

jobs:
  include:
    - stage: Run sbt with OpenJdk11
      os: linux
    - stage: Run sbt with OpenJdk11
      os: osx
    - stage: Generate coverage and scaladoc
      before_install:
        - sudo apt-get install python-pygments
      install:
        - source ./texlive/texlive_install.sh
      cache:
        directories:
          - /tmp/texlive
          - $HOME/.texlive
      script:
        - sbt coverage test coverageReport coverageAggregate doc
        - bash travis-scripts/deploy_to_pages.sh
        - travis_wait 3 pdflatex --shell-escape -output-directory public $TRAVIS_BUILD_DIR/source/doc/rel.tex
      deploy:
        provider: pages
        strategy: git
        skip_cleanup: true
        token: $GH_TOKEN
        keep_history: true
        local_dir: public
        on:
          all_branches: true
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: Deploy to Github Releases
      before_deploy:
        - sbt packArchive
      deploy:
        provider: releases
        skip_cleanup: true
        token: $GH_TOKEN
        file_glob: true
        file:
          - client/target/pack/client-*.zip
          - server/target/pack/server-*.zip
        on:
          branch: master
          tags: true

stages:
  - name: Run sbt with OpenJdk11
    if: type IN (pull_request, push) AND NOT branch = master
  - name: Generate coverage and scaladoc
    if: type = push AND branch IN (master, dev)
  - name: Deploy to Github Releases
    if: type = push AND branch = master
