# Info about vm and jvm.
language: scala # The project language.

jdk:
  - openjdk11 # Java version. Add other Java versions under this.

install: true

scala:
  # 2.12.11 # Scala version. Add other Scala versions under this.
  - 2.12.8 Last stable version

git:
  autocrlf: input

# These directories are cached to S3 at the end of the build.
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $HOME/.sbt/launchers

notifications:
  email:
    recipients:
      - daniele.tentoni.1996@gmail.com
      - mcavalluzzo.dev@gmail.com
      - lorenzo.pagnini@yahoo.com
      - lucagiorgit@virgilio.it
    on_failure: always
    on_success: change

jobs:
  include:
    - stage: Run sbt with OpenJdk11
      os: linux
      script: sbt test
    - stage: Run sbt with OpenJdk11
      os: osx
      script: sbt test
    - stage: Generate coverage and scaladoc
      script:
        - sbt clean coverage test coverageReport coverageAggregate doc package
        - bash <(curl -s https://codecov.io/bash)
      before_deploy:
        - bash travis-scripts/deploy_to_pages.sh
      deploy:
        provider: pages
        strategy: git
        skip_cleanup: true
        token: $GH_TOKEN
        keep_history: true
        local_dir: public
        on:
          all_branches: true

stages:
  - name: Run sbt with OpenJdk11
    if: type IN (pull_request, push)
  - name: Generate coverage and scaladoc
    if: type IN (pull_request, push) AND branch IN (master, dev)
